### ISSUE TITLE
Thymeleaf

### ISSUE THREAD

**Issue by hanhantt** [gujiniCY/mayday#7]
<pre><code class="lang-md hljs markdown">
            网站名称：<span th:text="${options['blog_name']}"></span>
            网站地址：<span th:text="${options['blog_url']}"></span></code></pre>
        <p>我的邮箱:<span th:text="${options['email_username']}"></span></p>

请问那个options是什么呀

**Comment by gujiniCY** [comment]
https://github.com/gujiniCY/mayday/blob/master/src/main/java/com/songhaozhi/mayday/web/interceptor/IndexInterceptor.java
